<?php

namespace Database\Seeders;

use App\Models\CalendarEvent;
use Illuminate\Database\Seeder;

class CalendarEventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            // holidays
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => 'Новый год',
                'description' => 'Государственный праздник',
                'start_date' => '2026-01-01',
                'end_date' => '2026-01-01',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 100,
            ],
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => 'Рождество',
                'description' => 'Праздничный день',
                'start_date' => '2026-01-07',
                'end_date' => '2026-01-07',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 95,
            ],
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => '8 марта',
                'description' => 'Международный женский день',
                'start_date' => '2026-03-08',
                'end_date' => '2026-03-08',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 92,
            ],
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => 'Пасха',
                'description' => 'Праздничный выходной',
                'start_date' => '2026-04-12',
                'end_date' => '2026-04-13',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 90,
            ],
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => '1 мая',
                'description' => 'Праздник труда',
                'start_date' => '2026-05-01',
                'end_date' => '2026-05-03',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 88,
            ],
            [
                'type' => CalendarEvent::TYPE_HOLIDAY,
                'title' => 'День Победы',
                'description' => 'Государственный праздник',
                'start_date' => '2026-05-09',
                'end_date' => '2026-05-09',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 97,
            ],

            // workflow
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Планёрка',
                'description' => 'Еженедельная встреча команды',
                'start_date' => '2026-01-05',
                'end_date' => '2026-01-05',
                'repeat_type' => CalendarEvent::REPEAT_WEEKLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 70,
            ],
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Проверка отчётов',
                'description' => 'Еженедельная проверка отчетности',
                'start_date' => '2026-01-08',
                'end_date' => '2026-01-08',
                'repeat_type' => CalendarEvent::REPEAT_WEEKLY,
                'repeat_until' => '2026-12-31',
                'is_active' => true,
                'priority' => 66,
            ],
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Сдача графика',
                'description' => 'Ежемесячное утверждение графика',
                'start_date' => '2026-01-25',
                'end_date' => '2026-01-25',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 80,
            ],
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Инвентаризация',
                'description' => 'Проверка наличия оборудования',
                'start_date' => '2026-02-15',
                'end_date' => '2026-02-17',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => '2026-12-31',
                'is_active' => true,
                'priority' => 75,
            ],
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Аттестация персонала',
                'description' => 'Период внутренней оценки сотрудников',
                'start_date' => '2026-04-20',
                'end_date' => '2026-04-24',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 84,
            ],
            [
                'type' => CalendarEvent::TYPE_WORKFLOW,
                'title' => 'Обучение новых сотрудников',
                'description' => 'Вводный цикл обучения',
                'start_date' => '2026-09-01',
                'end_date' => '2026-09-14',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 72,
            ],

            // finance
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Зарплата',
                'description' => 'Ежемесячная выплата зарплаты',
                'start_date' => '2026-01-10',
                'end_date' => '2026-01-10',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 90,
            ],
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Аванс',
                'description' => 'Ежемесячная выплата аванса',
                'start_date' => '2026-01-25',
                'end_date' => '2026-01-25',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 85,
            ],
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Оплата аренды',
                'description' => 'Ежемесячная оплата аренды помещения',
                'start_date' => '2026-01-03',
                'end_date' => '2026-01-03',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 60,
            ],
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Налоговый отчёт',
                'description' => 'Квартальная сдача налогового отчета',
                'start_date' => '2026-03-31',
                'end_date' => '2026-04-02',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => '2026-12-31',
                'is_active' => true,
                'priority' => 95,
            ],
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Годовой бюджет',
                'description' => 'Подготовка и согласование бюджета',
                'start_date' => '2026-11-15',
                'end_date' => '2026-11-30',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 93,
            ],
            [
                'type' => CalendarEvent::TYPE_FINANCE,
                'title' => 'Сверка платежей',
                'description' => 'Проверка оплат и задолженностей',
                'start_date' => '2026-02-05',
                'end_date' => '2026-02-06',
                'repeat_type' => CalendarEvent::REPEAT_MONTHLY,
                'repeat_until' => '2026-10-31',
                'is_active' => true,
                'priority' => 68,
            ],

            // peak
            [
                'type' => CalendarEvent::TYPE_PEAK,
                'title' => 'Высокая загрузка летом',
                'description' => 'Летний сезон максимальной нагрузки',
                'start_date' => '2026-06-01',
                'end_date' => '2026-08-31',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 85,
            ],
            [
                'type' => CalendarEvent::TYPE_PEAK,
                'title' => 'Новогодний пик',
                'description' => 'Повышенная загрузка перед Новым годом',
                'start_date' => '2026-12-20',
                'end_date' => '2026-12-31',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 100,
            ],
            [
                'type' => CalendarEvent::TYPE_PEAK,
                'title' => 'Период отпусков',
                'description' => 'Много сотрудников в отпуске',
                'start_date' => '2026-07-10',
                'end_date' => '2026-07-31',
                'repeat_type' => CalendarEvent::REPEAT_YEARLY,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 70,
            ],
            [
                'type' => CalendarEvent::TYPE_PEAK,
                'title' => 'Осенний наплыв клиентов',
                'description' => 'Короткий период высокой нагрузки',
                'start_date' => '2026-10-01',
                'end_date' => '2026-10-10',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 78,
            ],
            [
                'type' => CalendarEvent::TYPE_PEAK,
                'title' => 'Пик выходных бронирований',
                'description' => 'Регулярный всплеск активности по выходным',
                'start_date' => '2026-01-10',
                'end_date' => '2026-01-11',
                'repeat_type' => CalendarEvent::REPEAT_WEEKLY,
                'repeat_until' => '2026-06-30',
                'is_active' => true,
                'priority' => 74,
            ],

            // strike
            [
                'type' => CalendarEvent::TYPE_STRIKE,
                'title' => 'Забастовка транспорта',
                'description' => 'Перебои в работе общественного транспорта',
                'start_date' => '2026-05-15',
                'end_date' => '2026-05-16',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 100,
            ],
            [
                'type' => CalendarEvent::TYPE_STRIKE,
                'title' => 'Забастовка аэропорта',
                'description' => 'Возможны задержки и отмены рейсов',
                'start_date' => '2026-06-20',
                'end_date' => '2026-06-22',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 95,
            ],
            [
                'type' => CalendarEvent::TYPE_STRIKE,
                'title' => 'Забастовка метро',
                'description' => 'Частично не работает метро',
                'start_date' => '2026-09-03',
                'end_date' => '2026-09-03',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 90,
            ],
            [
                'type' => CalendarEvent::TYPE_STRIKE,
                'title' => 'Региональная забастовка',
                'description' => 'Ограничения в работе части сервисов',
                'start_date' => '2026-10-12',
                'end_date' => '2026-10-15',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => true,
                'priority' => 82,
            ],
            [
                'type' => CalendarEvent::TYPE_STRIKE,
                'title' => 'Предупредительная забастовка',
                'description' => 'Тестовая неактивная запись',
                'start_date' => '2026-11-10',
                'end_date' => '2026-11-10',
                'repeat_type' => CalendarEvent::REPEAT_NONE,
                'repeat_until' => null,
                'is_active' => false,
                'priority' => 40,
            ],
        ];

        foreach ($events as $event) {
            CalendarEvent::updateOrCreate(
                [
                    'type' => $event['type'],
                    'title' => $event['title'],
                    'start_date' => $event['start_date'],
                ],
                $event
            );
        }
    }
}