<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name' => 'Алексей Иванов',
                'email' => 'alexey@example.com',
                'telegram_id' => '100001',
                'telegram_username' => 'alexey_ivanov',
                'telegram_photo_url' => null,
                'role' => 'admin',
                'status' => 'approved',
                'approved_at' => now()->subDays(30),
                'approved_by' => 1,
                'last_login_at' => now()->subHours(2),
                'birthday' => Carbon::parse('1998-03-12'),
                'work_started_at' => Carbon::parse('2024-01-15'),
                'dip' => false,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Мария Смирнова',
                'email' => 'maria@example.com',
                'telegram_id' => '100002',
                'telegram_username' => 'maria_smirnova',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(20),
                'approved_by' => 1,
                'last_login_at' => now()->subDay(),
                'birthday' => Carbon::parse('1995-07-21'),
                'work_started_at' => Carbon::parse('2024-02-10'),
                'dip' => true,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Дмитрий Кузнецов',
                'email' => 'dmitry@example.com',
                'telegram_id' => '100003',
                'telegram_username' => 'dmitry_k',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(18),
                'approved_by' => 1,
                'last_login_at' => now()->subDays(2),
                'birthday' => Carbon::parse('1993-11-05'),
                'work_started_at' => Carbon::parse('2024-03-01'),
                'dip' => false,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Ольга Петрова',
                'email' => 'olga@example.com',
                'telegram_id' => '100004',
                'telegram_username' => 'olga_pet',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(15),
                'approved_by' => 1,
                'last_login_at' => now()->subDays(3),
                'birthday' => Carbon::parse('1991-01-18'),
                'work_started_at' => Carbon::parse('2024-03-15'),
                'dip' => true,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Ирина Волкова',
                'email' => 'irina@example.com',
                'telegram_id' => '100005',
                'telegram_username' => 'irina_volkova',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'pending',
                'approved_at' => null,
                'approved_by' => null,
                'last_login_at' => null,
                'birthday' => Carbon::parse('2000-09-09'),
                'work_started_at' => Carbon::parse('2024-04-01'),
                'dip' => false,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Сергей Орлов',
                'email' => 'sergey@example.com',
                'telegram_id' => '100006',
                'telegram_username' => 'sergey_orlov',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(10),
                'approved_by' => 1,
                'last_login_at' => now()->subHours(10),
                'birthday' => Carbon::parse('1997-05-30'),
                'work_started_at' => Carbon::parse('2024-04-12'),
                'dip' => false,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Анна Соколова',
                'email' => 'anna@example.com',
                'telegram_id' => '100007',
                'telegram_username' => 'anna_sokolova',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(8),
                'approved_by' => 1,
                'last_login_at' => now()->subDays(1),
                'birthday' => Carbon::parse('1994-12-14'),
                'work_started_at' => Carbon::parse('2024-05-01'),
                'dip' => true,
                'is_active' => false,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Никита Морозов',
                'email' => 'nikita@example.com',
                'telegram_id' => '100008',
                'telegram_username' => 'nikita_morozov',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'rejected',
                'approved_at' => null,
                'approved_by' => null,
                'last_login_at' => null,
                'birthday' => Carbon::parse('2001-06-02'),
                'work_started_at' => Carbon::parse('2024-05-18'),
                'dip' => false,
                'is_active' => false,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Екатерина Лебедева',
                'email' => 'ekaterina@example.com',
                'telegram_id' => '100009',
                'telegram_username' => 'katya_lebedeva',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(5),
                'approved_by' => 1,
                'last_login_at' => now()->subHours(5),
                'birthday' => Carbon::parse('1996-08-27'),
                'work_started_at' => Carbon::parse('2024-06-01'),
                'dip' => true,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
            [
                'name' => 'Павел Фёдоров',
                'email' => 'pavel@example.com',
                'telegram_id' => '100010',
                'telegram_username' => 'pavel_fedorov',
                'telegram_photo_url' => null,
                'role' => 'cleaner',
                'status' => 'approved',
                'approved_at' => now()->subDays(3),
                'approved_by' => 1,
                'last_login_at' => now()->subMinutes(40),
                'birthday' => Carbon::parse('1992-10-10'),
                'work_started_at' => Carbon::parse('2024-06-20'),
                'dip' => false,
                'is_active' => true,
                'password' => Hash::make('password'),
            ],
        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['email' => $user['email']],
                $user
            );
        }
    }
}